name: iOS Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.6"
          bundler-cache: true
          working-directory: ios

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ios

      # Step 4: Set up Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Step 5: Set up Cocoapods
      - name: Install CocoaPods
        run: pod install
        working-directory: ios

      # Step 6: Build and Distribute
      - name: Build and Distribute iOS App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane ios firebase_distribution
        working-directory: ios
